version: '3'

networks:
  default:
    driver: bridge

services:
  php:
#    image: yiisoftware/yii2-php:7.4-apache
    build:
      context: ./docker/php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/xdebug.ini:/etc/php/7.4-apache/mods-available/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: "client_port=9000 start_with_request=yes idekey=netbeans-xdebug log_level=1 log=/app/xdebug.log discover_client_host=1"
      XDEBUG_MODE: "develop,debug"
    ports:
      - '80:80'
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'